# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f97eb9fdb4296e218e393db328a22f70398c371746a1838fc24a8dd793cc815ea08fae5e294a461d5771c0b12d53f285e68a9a939a886329d170709795cb2e6
  facebook_app_id: 452173128287414
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>

test:
  secret_key_base: b2e12fda3861152cadd1bca02c82b420cb4948ac795f22efd5474af7700b303b0d5fb8e85c603e5d718b5069f49d2241a908c84ae594d1ccf33fdea933bb1197
  facebook_app_id: 452173128287414
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: 452173128287414
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
